### ISSUE TITLE
Strange failure with mrtg-2.17.4 and rrdtool >1.4.8

### ISSUE THREAD

**Issue by UnixRonin** [oetiker/mrtg#10]
I have encountered a peculiar problem with mrtg and recent versions of rrdtool on a Gentoo Linux system.

Background:  I have two (and as far as I'm aware only two) applications that use rrdtool, mrtg and my own upswatch, a tool which uses rrdtool to monitor and graph UPS operating parameters via apcupsd.

If I allow rrdtool to update past release 1.4.8, mrtg still gathers traffic data, but fails to graph it, dying with the following error logged by Apache:

[Sun Mar 18 14:04:39.866602 2018] [cgi:error] [pid 19784:tid 140158795384576] [client 10.24.32.10:50654] AH01215: Undefined subroutine &RRDs::graph called at /var/www/mrtg/mrtg-rrd.cgi line 451.: /var/www/mrtg/mrtg-rrd.cgi, referer: https://www.caerllewys.net/mrtg2/

Yet upswatch continues to work perfectly all the way up to rrdtool-1.7.0.  This implies the problem is in mrtg, not in rrdtool.  But if the problem is in mrtg, then why does it depend on the rrdtool version?

**Comment by oetiker** [comment]
it is possible to compile librrd without graph support ... maybe this was the case here
