### ISSUE TITLE
noHC=yes incorrectly inserted by cfgmaker

### ISSUE THREAD

**Issue by durkovic** [oetiker/mrtg#108]
noHC=yes is inserted by cfgmaker not only when HC counters are unavailable, but also when interface has not yet seen any incoming traffic (ifHCInOctets=0).

Thus every unused interface initially gets noHC=yes, causing it to show bogus graphs when traffic starts to flow. After next cfgmaker run, it switches to HC counters, making huge spike in the graph.

**Comment by oetiker** [comment]
https://github.com/oetiker/mrtg/pull/109 does this help ?

**Comment by durkovic** [comment]
Sure, thanks!
