### ISSUE TITLE
ERROR: CFG Error in "workdir"

### ISSUE THREAD

**Issue by renatocfrancisco** [oetiker/mrtg#24]
ERROR: CFG Error in "workdir", file mrtg.cfg line 20: Working directory c:\www\mrtg does not exist

On the mrtg.cfg, i put 127.0.0.1 as my IP Address
and on the line 20 there is "Enable IPv6: no"

Is this normal? What am i doing wrong?
This is my mrtg file...
[gist](https://gist.github.com/renatocfrancisco/c77368ea2ce4f6bcd4d0d9544b558e2b)

**Comment by oetiker** [comment]
make sure the www\mrtg directory exists
