### ISSUE TITLE
new ifTypes needed

### ISSUE THREAD

**Issue by nistorj** [oetiker/mrtg#4]
Hi.

A number of network vendors and older software on those vendor gear report ifType 53 as IEEE 802.3ad interfaces.  More and more are moving the the IANA ifType assigned number of 161 (ref: https://www.ietf.org/assignments/ianaiftype-mib/ianaiftype-mib).

Today cfgmaker only supports entries types 1 through 142 then jumps to 162.  161 is:
                   ieee8023adLag (161),  -- IEEE 802.3ad Link Aggregate

Could you please add this (or maybe the rest of the list) into cfgmaker as well?

Thanks!

**Comment by nistorj** [comment]
Just to add to this, more IfTypes were added on Nov 23, https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib

**Comment by oetiker** [comment]
can you do a pull request ?

**Comment by nistorj** [comment]
merged
